-- return {
-- 	"nvim-telescope/telescope.nvim",
-- 	branch = "0.1.x",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
-- 		"nvim-tree/nvim-web-devicons",
-- 	},
-- 	config = function()
-- 		local telescope = require("telescope")
-- 		local actions = require("telescope.actions")
--
-- 		telescope.setup({
-- 			defaults = {
-- 				path_display = { "smart" },
-- 				file_ignore_pattern = { "node_modules", "dist", "lib", "ios", "android", "__snapshots__", "__snapshot__", "*.snap", "*.lock", "build", "Pods", "localizationRaw.*" },
--         preview = {
--           treesitter = false
--         },
-- 				mappings = {
-- 					i = {
-- 						["<C-k>"] = actions.move_selection_previous, -- move to prev result
-- 						["<C-j>"] = actions.move_selection_next, -- move to next result
-- 						["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
-- 					},
-- 				},
-- 			},
-- 		})
--
-- 		telescope.load_extension("fzf")
--
-- 		-- set keymaps
-- 		-- local keymap = vim.keymap -- for conciseness
--
--     -- keymap.set('n', '<leader>ff', "<CMD>lua require('telescope.builtin').find_files({debounce = 400})<CR>", { desc = 'Find files' })
-- 		-- keymap.set("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Fuzzy find recent files" })
--     -- keymap.set('n', '<leader>fs', "<CMD>lua require('telescope.builtin').live_grep({debounce = 1000})<CR>", { desc = 'Live grep' })
-- 		-- keymap.set("n", "<leader>fc", "<cmd>Telescope grep_string<cr>", { desc = "Find string under cursor in cwd" })
-- 		-- keymap.set("n", "<leader>ft", "<cmd>TodoTelescope<cr>", { desc = "Find todos" })
-- 	end,
-- }
